# Generated by Django 6.0.6 on 2026-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватарку",
                max_length=150,
                null=True,
                upload_to="",
                verbose_name="Аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=16,
                null=True,
                verbose_name="Телефон",
            ),
        ),
    ]
