# Generated by Django 6.0.6 on 2026-06-29 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Введите сумму", verbose_name="Сумма"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Укажите id сессии",
                        max_length=255,
                        null=True,
                        verbose_name="id_ сессии",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        null=True,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите полғзователә",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Полғзователғ",
                    ),
                ),
            ],
        ),
    ]
