# Generated by Django 6.0.6 on 2026-07-01 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_paymentdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="paid_lesson",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payments_date",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="user",
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="id  сессии"
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
