# Generated by Django 6.0.6 on 2026-07-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_subscription"),
        ("users", "0005_remove_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс оплачен",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Урок оплачен",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Суммы оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer_to_account", "Перевод на счёт"),
                ],
                default="cash",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payments_date",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату проведения платежа",
                null=True,
                verbose_name="Дата оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PaymentDetails",
        ),
    ]
