# Generated by Django 6.0.6 on 2026-06-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preview",
                    models.ImageField(
                        help_text="Загрузите картинку",
                        max_length=150,
                        upload_to="materials/photo",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Описание курса",
                        max_length=150,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Описание урока",
                        max_length=150,
                        null=True,
                        verbose_name="Урок",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Загрузите картинку",
                        max_length=150,
                        upload_to="materials/photo",
                        verbose_name="Картинка",
                    ),
                ),
                ("source_url", models.URLField(max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                    ),
                ),
            ],
        ),
    ]
