# Generated by Django 6.0.6 on 2026-06-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                default=1,
                help_text="Введите название урока",
                max_length=150,
                verbose_name="Название урока",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание курса",
                max_length=150,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание урока",
                max_length=150,
                null=True,
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видеоматериал",
                max_length=500,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
