# Generated by Django 6.0.6 on 2026-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_options_lesson_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание курса",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                default="Default Course",
                help_text="Введите название курса",
                max_length=100,
                verbose_name="Название курса",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание урока", null=True, verbose_name="Урок"
            ),
        ),
    ]
