# Generated by Django 6.0.6 on 2026-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_course_description_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку",
                max_length=150,
                null=True,
                upload_to="materials/photo",
                verbose_name="Картинка",
            ),
        ),
    ]
